cmake -S . -B build -Drms_ENABLE_CACHE=OFF -Drms_WARNINGS_AS_ERRORS=OFF -Drms_ENABLE_CLANG_TIDY=OFF -Drms_ENABLE_SANITIZER_ADDRESS=OFF -Drms_ENABLE_SANITIZER_UNDEFINED=OFF -Drms_ENABLE_SANITIZER_LEAK=OFF -Drms_ENABLE_SANITIZER_THREAD=OFF -Drms_ENABLE_SANITIZER_MEMORY=OFF
cmake --build build --parallel 12
